import { Project } from '@/types/project';

export const projects: Project[] = [
  /* ---------- Current healthcare and revenue-cycle work ---------- */
  {
    title: 'Healthcare Claims Automation Platform',
    category: 'Healthcare revenue cycle',
    era: 'current',
    stages: ['Claim intake', 'Validation', 'Business rules', 'Claim status'],
    description:
      'A revenue-cycle platform that turns incoming claim files into validated, classified, and trackable work through asynchronous processing and clearinghouse integrations.',
    problem:
      'Make imperfect claim data operationally useful while payer rules change and important state lives in external systems.',
    metric: 'From intake to a traceable work queue',
    technologies: [
      'Python',
      'Django',
      'Celery',
      'PostgreSQL',
      'React',
      'Stedi',
      'AWS',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/healthcare-claims-automation',
    details: true,
    isWorking: true,
    confidential: true,
  },
  {
    title: 'Scaling Healthcare Document Ingestion',
    category: 'Document processing',
    era: 'current',
    stages: ['Documents', 'Validation', 'Async workers', 'Structured data'],
    description:
      'Redesigned a healthcare document-ingestion path to avoid unnecessary page rendering while preserving support for scanned and mixed-content documents.',
    problem:
      'Keep unusually large and varied documents moving through production without turning every page into expensive temporary data.',
    metric: 'Faster, leaner processing grounded in real production behavior',
    technologies: [
      'Python',
      'PyMuPDF',
      'OCR',
      'Celery',
      'Amazon S3',
      'PostgreSQL',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/healthcare-document-ingestion',
    details: true,
    isWorking: true,
    confidential: true,
  },
  {
    title: 'Cloud Infrastructure & Production Engineering',
    category: 'Cloud infrastructure',
    era: 'current',
    stages: ['Build', 'Provision', 'Deploy', 'Operate'],
    description:
      'Containerized application and worker workloads on AWS, provisioned repeatable environments with Terraform, and shipped changes through GitHub Actions.',
    problem:
      'Give healthcare workloads private, reproducible infrastructure and safe operational paths for encrypted data and database changes.',
    metric: 'Private, repeatable, production-ready environments',
    technologies: [
      'AWS ECS',
      'RDS PostgreSQL',
      'S3',
      'ECR',
      'CloudFront',
      'Terraform',
      'GitHub Actions',
      'Docker',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/cloud-infrastructure',
    details: true,
    isWorking: true,
    confidential: true,
  },
  {
    title: 'Building Reliable Healthcare Workflows',
    category: 'Production reliability',
    era: 'current',
    stages: ['Observe', 'Recover', 'Re-run safely'],
    description:
      'A set of production improvements that make asynchronous healthcare workflows observable, recoverable, and safe to operate.',
    problem:
      'Prevent silent failures, preserve the right document-to-patient relationships, and make historical repair work safe to resume.',
    metric: 'No silent success; recovery is part of the workflow',
    technologies: [
      'Python',
      'Django',
      'Celery',
      'PyMuPDF',
      'Amazon S3',
      'PostgreSQL',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/reliable-healthcare-workflows',
    details: true,
    isWorking: true,
    confidential: true,
  },

  /* ---------- Earlier flagship case studies ---------- */
  {
    title: 'Deeply — AI Agent System for Couples',
    category: 'AI Systems',
    era: 'earlier',
    description:
      "A production LLM agent system that turns two partners' private inputs into one shared synthesis both recognize as fair — conversation engine, agent tools, artifact generation, and context assembly.",
    problem:
      'Synthesize two private perspectives into one fair, shared artifact — reliably, in production.',
    metric: 'A founding-engineer build from product idea to production',
    technologies: [
      'TypeScript',
      'Next.js',
      'Anthropic Claude SDK',
      'Langfuse',
      'Supabase / Postgres',
      'PostHog',
      'Sentry',
      'GitHub Actions',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/deeply',
    details: true,
    isWorking: true,
    confidential: true,
  },
  {
    title: 'AI Ticket Automation Platform',
    category: 'AI · Event-Driven',
    era: 'earlier',
    description:
      'Intelligent customer-support automation: AI intent classification and retention workflows over a distributed, idempotent ingestion pipeline with retries and dead-letter queues.',
    problem: 'Manual support-ticket triage did not scale with product usage.',
    metric: 'Reliable automation with recovery paths for failed work',
    technologies: [
      'Python',
      'FastAPI',
      'OpenAI',
      'AWS Lambda',
      'SQS',
      'API Gateway',
      'Redis',
      'Terraform',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/ai-ticket-automation',
    details: true,
    isWorking: true,
    confidential: true,
  },
  {
    title: 'Drools Credentialing Rules Engine',
    category: 'Backend · Rules Engine',
    era: 'earlier',
    description:
      'A Drools engine for healthcare-provider credentialing, with multi-tenant rule isolation and feature-flag-driven execution across health plans.',
    problem:
      'Encode payer-specific credentialing logic on one shared engine without cross-organization interference.',
    metric: 'Configurable rules without redeploying the application',
    technologies: ['Java', 'Drools', 'DRL', 'Spring Boot', 'JSON', 'Shell'],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/drools-credentialing-engine',
    details: true,
    isWorking: true,
    confidential: true,
  },
  {
    title: 'Multi-Source Analytics Aggregation Platform',
    category: 'Multi-Tenant SaaS',
    era: 'earlier',
    description:
      'A multi-tenant analytics platform aggregating external APIs into a unified, dependency-aware pipeline, with real-time sync tracking and token caching.',
    problem:
      'Aggregate records from many external APIs for multiple tenants, reliably and concurrently.',
    metric: 'Dependency-aware synchronization across isolated tenants',
    technologies: [
      'Python',
      'FastAPI',
      'PostgreSQL',
      'WebSockets',
      'Redis',
      'AsyncIO',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/analytics-aggregation-platform',
    details: true,
    isWorking: true,
    confidential: true,
  },

  /* ---------- Secondary work (cards only — high-level, no public links) ---------- */
  {
    title: 'Multi-Tenant Smart Irrigation Platform',
    category: 'Multi-Tenant SaaS',
    era: 'earlier',
    description:
      'Multi-tenant SaaS with role-based access control, an OAuth2 CRM sync engine with batch upserts, an offline-first PWA for field operations, and an automated email pipeline with SMTP failover.',
    metric: 'Offline-first field operations',
    technologies: ['Django', 'React', 'PostgreSQL', 'Docker', 'PWA'],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/smart-irrigation',
    details: false,
    isWorking: false,
    confidential: true,
  },
  {
    title: 'Mobex Health Suite',
    category: 'Healthcare',
    era: 'earlier',
    description:
      'Real-time patient monitoring with a Flutter QR-based onboarding module and an AWS deployment supported by database redundancy and operational alerting.',
    metric: 'Connected monitoring and smoother patient onboarding',
    technologies: ['Java', 'Flutter', 'AWS', 'MySQL', 'CloudWatch'],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/mobex',
    details: false,
    isWorking: false,
    confidential: true,
  },
  {
    title: 'Infozech iTower Link',
    category: 'Mobile · Telecom',
    era: 'earlier',
    description:
      'Re-engineered a telecom tower-management app with an offline-first architecture for field technicians, plus Java middleware for large-scale asset synchronization.',
    metric: 'Offline-first field operations',
    technologies: ['Flutter', 'Java', 'AWS'],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/itower-link',
    details: false,
    isWorking: false,
    confidential: true,
  },

  /* ---------- Open source / public projects (with links) ---------- */
  {
    title: 'Coupon Management API',
    category: 'Open Source',
    era: 'open-source',
    description:
      'Production-ready REST API for e-commerce discounts — cart-wise, product-wise, and BxGy (Buy X Get Y) — with validation, usage limits, expiration handling, and Swagger docs.',
    technologies: [
      'Node.js',
      'Express.js',
      'PostgreSQL',
      'Supabase',
      'Docker',
      'Jest',
      'Swagger',
    ],
    github: 'https://github.com/Jainshashank7125/coupon-management-api',
    live: 'https://coupon-management-api.onrender.com',
    link: '',
    image: '',
    projectDetailsPageSlug: '',
    details: false,
    isWorking: true,
  },
  {
    title: 'WhiteCarrot ATS — Careers Page Builder',
    category: 'Open Source',
    era: 'open-source',
    description:
      'Multi-tenant careers-page builder letting recruiters create branded company pages with custom sections, job listings, CSV bulk import, per-user drafts, and secure preview tokens.',
    technologies: [
      'Next.js',
      'React',
      'TypeScript',
      'Supabase',
      'PostgreSQL',
      'Tailwind CSS',
    ],
    github: 'https://github.com/Jainshashank7125/whitecarrort-ats-branded',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '',
    details: false,
    isWorking: true,
  },
  {
    title: 'AI Agent Form — Intelligent Copilot',
    category: 'Open Source',
    era: 'open-source',
    description:
      'A Next.js app with an AI copilot that guides users through form submission with real-time form updates, conversational AI, and step-by-step field validation.',
    technologies: ['Next.js', 'TypeScript', 'React', 'Tailwind CSS', 'Gemini API'],
    github: 'https://github.com/Jainshashank7125/ai-agent-idea',
    live: 'https://ai-agent-idea.vercel.app/',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/ai-agent-form',
    details: false,
    isWorking: true,
  },
];
