import { Project } from '@/types/project';

export const projects: Project[] = [
  /* ---------- Current: healthcare RCM case studies (high-level, no links) ---------- */
  {
    title: 'Healthcare Claims Automation Platform',
    category: 'Healthcare revenue cycle',
    stages: ['Claim intake', 'Rules', 'Clearinghouse', 'Denied'],
    description:
      'An RCM platform that ingests claim files, routes every claim through configurable business rules into operational buckets, and keeps claim status current through clearinghouse integrations.',
    problem:
      'Turn high-volume, imperfect claim data into correctly classified, trackable claims — where payer rules change often and much of the state lives in external systems.',
    metric: 'From upload to claim status to work queue',
    technologies: [
      'Python',
      'Django',
      'Celery',
      'PostgreSQL',
      'React',
      'Stedi',
      'AWS',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/healthcare-claims-automation',
    details: true,
    isWorking: true,
    confidential: true,
  },
  {
    title: 'Scaling Healthcare Document Ingestion',
    category: 'Performance',
    stages: ['Documents'],
    description:
      'Redesigned the PDF-processing path of a healthcare document-ingestion pipeline so pages are rendered as images only when needed — while keeping scanned and mixed-content support.',
    problem:
      'A real 14,400-page (~100 MB) PDF took ~19 minutes and ~5.5 GB of temporary images to ingest.',
    metric: '~19 min to ~85 s on a 14,400-page PDF',
    technologies: [
      'Python',
      'PyMuPDF',
      'OCR',
      'Celery',
      'Amazon S3',
      'PostgreSQL',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/healthcare-document-ingestion',
    details: true,
    isWorking: true,
    confidential: true,
  },
  {
    title: 'Cloud Infrastructure & Production Engineering',
    category: 'Cloud infrastructure',
    stages: ['AWS'],
    description:
      'Containerized app and worker workloads on AWS, provisioned with Terraform and shipped through GitHub Actions — plus cross-account, cross-region database refresh and migration workflows.',
    problem:
      'Run healthcare workloads on private, reproducible infrastructure — and move encrypted databases between accounts and regions safely.',
    metric: 'Private, reproducible AWS environments',
    technologies: [
      'AWS ECS',
      'RDS PostgreSQL',
      'S3',
      'ECR',
      'CloudFront',
      'Terraform',
      'GitHub Actions',
      'Docker',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/cloud-infrastructure',
    details: true,
    isWorking: true,
    confidential: true,
  },
  {
    title: 'Building Reliable Healthcare Workflows',
    category: 'Reliability',
    stages: ['Async workers', 'Documents'],
    description:
      'A set of fixes that make asynchronous healthcare workflows reliable, recoverable, observable, and safe to operate — from false-success detection to idempotent backfills and safer user onboarding.',
    problem:
      'Async pipelines that reported success when processing had failed, lost patient documents, or served the wrong file.',
    metric: 'No silent failures, safe to re-run',
    technologies: [
      'Python',
      'Django',
      'Celery',
      'PyMuPDF',
      'Amazon S3',
      'PostgreSQL',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/reliable-healthcare-workflows',
    details: true,
    isWorking: true,
    confidential: true,
  },

  /* ---------- Earlier case studies (previous roles) ---------- */
  {
    title: 'Deeply — AI Agent System for Couples',
    category: 'AI Systems',
    description:
      "A production LLM agent system that turns two partners' private inputs into one shared synthesis both recognize as fair — conversation engine, agent tools, artifact generation, and context assembly.",
    problem:
      'Synthesize two private perspectives into one fair, shared artifact — reliably, in production.',
    metric: 'Founding-engineer build, zero to one',
    technologies: [
      'TypeScript',
      'Next.js',
      'Anthropic Claude SDK',
      'Langfuse',
      'Supabase / Postgres',
      'PostHog',
      'Sentry',
      'GitHub Actions',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/deeply',
    details: true,
    earlier: true,
    isWorking: true,
    confidential: true,
  },
  {
    title: 'AI Ticket Automation Platform',
    category: 'AI and event-driven systems',
    description:
      'Intelligent customer-support automation: AI intent classification and retention workflows over a distributed, idempotent ingestion pipeline with retries and dead-letter queues.',
    problem: 'Manual triage of 10K+ monthly support tickets did not scale.',
    metric: '70% less manual work',
    technologies: [
      'Python',
      'FastAPI',
      'OpenAI',
      'AWS Lambda',
      'SQS',
      'API Gateway',
      'Redis',
      'Terraform',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/ai-ticket-automation',
    details: true,
    earlier: true,
    isWorking: true,
    confidential: true,
  },
  {
    title: 'Drools Credentialing Rules Engine',
    category: 'Rules engine',
    description:
      'A 300+ rule Drools engine enforcing healthcare-provider credentialing compliance, with multi-tenant rule isolation and feature-flag-driven execution across health plans.',
    problem:
      'Encode payer-specific credentialing logic for 15+ health plans on one shared engine — without cross-org interference.',
    metric: '300+ rules across 15+ organizations',
    technologies: ['Java', 'Drools', 'DRL', 'Spring Boot', 'JSON', 'Shell'],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/drools-credentialing-engine',
    details: true,
    earlier: true,
    isWorking: true,
    confidential: true,
  },
  {
    title: 'Multi-Source Analytics Aggregation Platform',
    category: 'Multi-Tenant SaaS',
    description:
      'A multi-tenant analytics platform aggregating 3+ external APIs into a unified, dependency-aware pipeline, with real-time sync tracking over WebSockets and Redis token caching.',
    problem:
      'Aggregate 50K+ daily records from many external APIs for 50+ tenants, reliably and concurrently.',
    metric: '50K+ daily records, 99.9% uptime',
    technologies: [
      'Python',
      'FastAPI',
      'PostgreSQL',
      'WebSockets',
      'Redis',
      'AsyncIO',
    ],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/analytics-aggregation-platform',
    details: true,
    earlier: true,
    isWorking: true,
    confidential: true,
  },

  /* ---------- Secondary work (cards only — high-level, no public links) ---------- */
  {
    title: 'Multi-Tenant Smart Irrigation Platform',
    category: 'Multi-Tenant SaaS',
    description:
      'Multi-tenant SaaS with role-based access control, an OAuth2 CRM sync engine with batch upserts, an offline-first PWA for field operations, and an automated email pipeline with SMTP failover.',
    metric: 'Offline-first field operations',
    technologies: ['Django', 'React', 'PostgreSQL', 'Docker', 'PWA'],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/smart-irrigation',
    details: false,
    isWorking: false,
    confidential: true,
  },
  {
    title: 'Mobex Health Suite',
    category: 'Healthcare',
    description:
      'Real-time patient monitoring processing 50K+ daily events, with a Flutter QR-based onboarding module and AWS RDS multi-AZ deployment with CloudWatch alerting.',
    metric: '50K+ daily events, 60% faster check-in',
    technologies: ['Java', 'Flutter', 'AWS', 'MySQL', 'CloudWatch'],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/mobex',
    details: false,
    isWorking: false,
    confidential: true,
  },
  {
    title: 'Infozech iTower Link',
    category: 'Mobile, telecom',
    description:
      'Re-engineered telecom tower-management app with an offline-first architecture for 500+ field technicians, plus Java middleware integrating the AWS SDK for large-scale asset synchronization.',
    metric: '500+ field technicians',
    technologies: ['Flutter', 'Java', 'AWS'],
    github: '',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/itower-link',
    details: false,
    isWorking: false,
    confidential: true,
  },

  /* ---------- Open source / public projects (with links) ---------- */
  {
    title: 'Coupon Management API',
    category: 'Open Source',
    description:
      'Production-ready REST API for e-commerce discounts — cart-wise, product-wise, and BxGy (Buy X Get Y) — with validation, usage limits, expiration handling, and Swagger docs.',
    technologies: [
      'Node.js',
      'Express.js',
      'PostgreSQL',
      'Supabase',
      'Docker',
      'Jest',
      'Swagger',
    ],
    github: 'https://github.com/Jainshashank7125/coupon-management-api',
    live: 'https://coupon-management-api.onrender.com',
    link: '',
    image: '',
    projectDetailsPageSlug: '',
    details: false,
    isWorking: true,
  },
  {
    title: 'WhiteCarrot ATS — Careers Page Builder',
    category: 'Open Source',
    description:
      'Multi-tenant careers-page builder letting recruiters create branded company pages with custom sections, job listings, CSV bulk import, per-user drafts, and secure preview tokens.',
    technologies: [
      'Next.js',
      'React',
      'TypeScript',
      'Supabase',
      'PostgreSQL',
      'Tailwind CSS',
    ],
    github: 'https://github.com/Jainshashank7125/whitecarrort-ats-branded',
    live: '',
    link: '',
    image: '',
    projectDetailsPageSlug: '',
    details: false,
    isWorking: true,
  },
  {
    title: 'AI Agent Form — Intelligent Copilot',
    category: 'Open Source',
    description:
      'A Next.js app with an AI copilot that guides users through form submission with real-time form updates, conversational AI, and step-by-step field validation.',
    technologies: [
      'Next.js',
      'TypeScript',
      'React',
      'Tailwind CSS',
      'Gemini API',
    ],
    github: 'https://github.com/Jainshashank7125/ai-agent-idea',
    live: 'https://ai-agent-idea.vercel.app/',
    link: '',
    image: '',
    projectDetailsPageSlug: '/projects/ai-agent-form',
    details: false,
    isWorking: true,
  },
];
